package com.POJOs;
// Generated Dec 7, 2014 1:12:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer cmtId;
     private int postId;
     private int replyCmtId;
     private int userId;
     private Date creationTime;
     private String text;

    public Comment() {
    }

    public Comment(int postId, int replyCmtId, int userId, Date creationTime, String text) {
       this.postId = postId;
       this.replyCmtId = replyCmtId;
       this.userId = userId;
       this.creationTime = creationTime;
       this.text = text;
    }
   
    public Integer getCmtId() {
        return this.cmtId;
    }
    
    public void setCmtId(Integer cmtId) {
        this.cmtId = cmtId;
    }
    public int getPostId() {
        return this.postId;
    }
    
    public void setPostId(int postId) {
        this.postId = postId;
    }
    public int getReplyCmtId() {
        return this.replyCmtId;
    }
    
    public void setReplyCmtId(int replyCmtId) {
        this.replyCmtId = replyCmtId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


