package com.POJOs;
// Generated Dec 7, 2014 1:12:51 AM by Hibernate Tools 4.3.1



/**
 * ContactInfo generated by hbm2java
 */
public class ContactInfo  implements java.io.Serializable {


     private Integer userId;
     private String call1;
     private String call2;
     private String text1;
     private String text2;
     private String email1;
     private String email2;

    public ContactInfo() {
    }

    public ContactInfo(String call1, String call2, String text1, String text2, String email1, String email2) {
       this.call1 = call1;
       this.call2 = call2;
       this.text1 = text1;
       this.text2 = text2;
       this.email1 = email1;
       this.email2 = email2;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getCall1() {
        return this.call1;
    }
    
    public void setCall1(String call1) {
        this.call1 = call1;
    }
    public String getCall2() {
        return this.call2;
    }
    
    public void setCall2(String call2) {
        this.call2 = call2;
    }
    public String getText1() {
        return this.text1;
    }
    
    public void setText1(String text1) {
        this.text1 = text1;
    }
    public String getText2() {
        return this.text2;
    }
    
    public void setText2(String text2) {
        this.text2 = text2;
    }
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }




}


