package com.POJOs;
// Generated Dec 7, 2014 1:12:51 AM by Hibernate Tools 4.3.1



/**
 * FeedTag generated by hbm2java
 */
public class FeedTag  implements java.io.Serializable {


     private FeedTagId id;

    public FeedTag() {
    }

    public FeedTag(FeedTagId id) {
       this.id = id;
    }
   
    public FeedTagId getId() {
        return this.id;
    }
    
    public void setId(FeedTagId id) {
        this.id = id;
    }




}


