package com.POJOs;
// Generated Dec 7, 2014 1:12:51 AM by Hibernate Tools 4.3.1



/**
 * FeedTagId generated by hbm2java
 */
public class FeedTagId  implements java.io.Serializable {


     private int userId;
     private String tag;

    public FeedTagId() {
    }

    public FeedTagId(int userId, String tag) {
       this.userId = userId;
       this.tag = tag;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FeedTagId) ) return false;
		 FeedTagId castOther = ( FeedTagId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getTag()==castOther.getTag()) || ( this.getTag()!=null && castOther.getTag()!=null && this.getTag().equals(castOther.getTag()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getTag() == null ? 0 : this.getTag().hashCode() );
         return result;
   }   


}


