package com.POJOs;
// Generated Dec 7, 2014 1:12:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer postId;
     private Date creationTime;
     private Integer userId;
     private Boolean status;
     private String title;
     private String type;
     private Integer condi;
     private float price;
     private String body;
     private String imgUrl;
     private int likeCount;

    public Post() {
    }

	
    public Post(String title, String type, float price, String body, int likeCount) {
        this.title = title;
        this.type = type;
        this.price = price;
        this.body = body;
        this.likeCount = likeCount;
    }
    public Post(Date creationTime, Integer userId, Boolean status, String title, String type, Integer condi, float price, String body, String imgUrl, int likeCount) {
       this.creationTime = creationTime;
       this.userId = userId;
       this.status = status;
       this.title = title;
       this.type = type;
       this.condi = condi;
       this.price = price;
       this.body = body;
       this.imgUrl = imgUrl;
       this.likeCount = likeCount;
    }
   
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getCondi() {
        return this.condi;
    }
    
    public void setCondi(Integer condi) {
        this.condi = condi;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public int getLikeCount() {
        return this.likeCount;
    }
    
    public void setLikeCount(int likeCount) {
        this.likeCount = likeCount;
    }




}


